apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgAZPsd9QHuyMOOaDiBOd3iLSyPDOoUqGGDpDZaMzAOR1iib3cCPjcoo+WthGq3gqhxw9DBrP0GvOg4WvSstPhyTWhVpSvSRTW9MfG8x+QPvUH0V6a6mEjoNKObQzmZDhZ7hUgcSLs4LY5WcRRvMT3JDjTz4OIsRu/nkj7EmvLOl01gPKr7mO+WzhD01P/Y07UCBhImY1+PYnPtu4UOlHLyfZVptAZVu1+ejw6RpNW1bAAlAqlIY90U08I/11K42aM+GQ0EZcuDhqyVShTeUVMpJSu6qDHl84+xUcZrRMOst9A+GAIX88Z+RwehD4th1iJUNhcRolrX4/6cu1qFIaQ1+QRvtIerdhCnvjHTCBqt3+MEIQq+iIAx6iJxr6uAMFbehGTLzZ8CpuwhY+rU2fcnOegwycNs+hXVdji/Yfzn0taa9YR96ijzZdcTE8YJisUP72n/DDEEdUe42uzKJib+BOiWnnWZwu8vRXeLwc4m+Qbsh5TGAVYYy3bXDWxqhKjp0d4nzn4LSDKPNIH4CXoAqzS22UENrG4KVN2sWA3bQuof3Mmm2o6rXK9E50ppUlywB4EDuBMOnwg7oMq/QTnaOUGWA+7wzo2ZW5KaQiYb9iJEctFpibqL4hUupdFaRoUY/9x7ZnDHUJteNIKVi66kgbic+ZMxpgkTBjCbAjfCagxIWQwtl8NzSqopNmPqLpC8qo1KAix6t4a4BEt8=
    username: AgASCFcj6ITuQlGYORHvGZC6imeuLqb9eMkkZfD+Rp4NhxLkcQV0Not/fyaB++VdONiML2wM1QqbxXFnDg7TR8DIj+D4R/mDpBwOFIBO2oGkOP9+B07lJCeJOkJOGzdqrnlBYqaWELqmyY0UA6XsnWX9eLLbdeVzn+eS2bZlS+dByr/Wy/+dKKLZ5PrDHB2bmu99Ur05ISV0x35RTh5QPYLIqWlrzmv4JxZBe9LGicjCfK99EzSBAEaiiqbrY4XVKc6y45zAanQK/DdnzQ8M7CxdqxrvYhoe4iQ47mz2t8RJN98OdMdvKpe//QQyy0uBCTthJxFqdeqPtimpIwGcR5sRIs62eO6ALUcb50i1yBfohSRePH9yM1cxXkCp7Ao7CWiKca2io71sBzYlD479KYoqkKuRM2ZrhTpOAchaH6tEtJCar0CdtDGsdopp9KDDUQ2+/tBwV1m55gDouZ85WLfXeCYEhcGqrEq0ykYDFxUjrYLb6oEM1nZc5eGvQKcZ4jgehZGL38cZfjv1r3KBcPsVv8/qppNhSmE4t4z+5EiQosicUXjsLgO6hLamekDugE1LkXyeQrEFV+OGon5QDz8hx82+KVrkpSUc03Og6Iu0X+mO+RJ0052jphbwn2V16Yg+vZiosKcyW1HcmVp/Mr3/OAowekaafL99uqTesoGDeYusuA5rNqAMWkwEUy78MrN8pDf6V1U=
  template:
    metadata:
      creationTimestamp: null
      name: {{.Chart.Name }}-index2
      namespace: default
    type: Opaque
