apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{.Chart.Name }}-index2
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: AgBOetrszfhALagHjddEvTjCyA8s++yec/Z/1o9wdGSx8+qbymGNWO736hEWNbe9DLBmcGnLKVJtR28KSBdg1hq+l/A8xnfyBGDXZ1EUT7tRqa/i/r1QOAEa49Dp7TLFwG2Lok2xiuxpwohQsVtJtTBAs9fUArFyYJ80DyvAYkmpUZEtxhj1t21lJwjqFM/XCC1NosVSeDiHBcJlO46p93oYd3AGVEKuyca1xrvOYCxTvfS2bZz5PPkJWz0Rn2j5tQcw4UKUn7z49sRfL0OiuwPrKuiJUODliNpqG2Yu4ADfcWlpSl4VIGJSgp0wl3ZKiwjuV76xexTRvpPz4W1GX5wG+M4tfwjq/6kUPP928OOI7z4fFI6aGtjnU71GoRfL79StrkrPpTRy34EvsN1LwU88Qt34QhxJOG+85Eq6B3VrwwPxENYf3tiArWPpkQ/gSXGZzvT/YZLO6TRYjRxsHI9ay+qOugXwlXuQdOyYVEGMX2KbO30cUins8ZIsX5x9eq3CrBTJMjU07c+Z9M2J1uAu0SYjstGeQa9E+3+8+hnwiGux5fWermmeCjDg9TRo2jC+JhtKIOayIq4P8q+YaLF/nqyQWOppdGrFV1zRy7RTKzQD6EXeSnkffnmbSqt/+giBTy+XjMaE3Xrz03DB/XrEg9h1fuYqX4/pvFLAc824cAuBfDNpWL3WxDcjme6GuQkSIK9Uemr8lMzyXQ==
    username: AgCo+fguTHGmj3HcTaDPY+EfPtoTNGIlx6wJvT0ScCuSMFfQt9fzqVGUfN6tx5QPlMOU2/4qZVdjsdDcwdJWlfydR1WWc4YWzHb6byNGjbugq55frozjtXZVSiHIIFaofu0TFUcqT/5B8RNtIS2RylOzUarTyMT034E/jqT9UFt7K/TFNrZGLZZHACM7E7+LSTqYPSXFj6/eIxyONXsVAidfvqx2auEj9iATjdKT/2BIaQjZAOL7z8lnJF4bnwbsW6DwQimImleKEIPES3ilYECUrZ2jJDOJD3QlhL3BtIfIl6TVo4F9kM1G1qjqTVwYmHlhQSpQfRpNWuoSvD78Vl/gO4iLKFUzu0RysfYAhxosT4SsQ0iLT5mVzaDWI5gmyn1T3U+DhWxYjh4J/Jhteg0EUWZoyaUsU3cbPiVPdNyDqPZrKYcZxLCp9Rn5yeZErt5kRlHztuvDwzTP+pZw9LaoQAVflFTSsPUi3Vpx2KhRL2I8nEla4SN64rdvotS6morHQfDaF8ebpcnOCpS81ktcwS18AcFAe9YC4Bn3uHCyK4fwYRTPq7cwGxVocEG9gDsynt+8s13LhKbBewj5oxyBRxP5z3hYoGpMrn0DauwKJAaeN8zKaevYL4C8gtPkbcXUyDUIIB7ZLOzEugfO7Wvw/DrZl+fpkupW/9xqpoclukBAfLivwBl2GcV+vz6i2rFpWs4EfUn0
  template:
    metadata:
      creationTimestamp: null
      name: {{.Chart.Name }}-index2
      namespace: default
    type: Opaque
