apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{.Chart.Name }}-index2
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: AgCglWc0e66ip3ZJVRR53jGG77IEa6C1d3geaafB5pTwdsYyNKNIhPGHN7JlyR9f0EINBq9EugjFBC2/RHL5ADQaW0Uc50c/J/8ueXQmtNQtT2dYs1ZxU1FEgmVMlKX3NgK01aGdXdx+2r+cUbIOTdNf6y60wRwLx4otm+RzkkbaGBfD7L1efEsyKYD6Ify6H5LI0elvk+/tUX/hLFK+OwXlVue3TRrPtQzlujFTu3CfUQJcW2FPmRbDLaEFqD/cOs8rq9nW/QBwThzcuAkqm3g9dBNjKbrpNcyYEm7n1Ul8jAoYv02TBZqaE/Mv1kT6ww1LSZ0s33mkfZTYE51P59KUPJE3mxpAUZm6X5yHIyhimfazliqqGG0jnaEOzSDbWl5AymJehA4VWRb4pMK0LCfcBsVxQ9ZsxUK8aEKQ466EbRNdv7TXzcCl8IDUusFo/gUX7Pfc1ua86lGeCv1BKuNL/RCRqRbaqNRfP0rU5WHAe0lK203Z8SKlp3ETFi8QopPoKPr5RORkNaohG8bNYT9KHqmqnZm2YijlkVaS0GJlZv8/MoVUJCqQn/89eAQ6SLmGlgZ8S4LZxl/gOOOrzBMuFrYwFtPPAC0Yt/C+BqE1NgP3sb/g7n8Ca1evAuvy2TYJNf9jd3Ff/209FWNDJ9Rm34q0OKpbm5h09SxICQb3CP89LgY1luQd1VCmjPSPW82Eo62kduZlP5tBjok2p1s=
    username: AgCo+fguTHGmj3HcTaDPY+EfPtoTNGIlx6wJvT0ScCuSMFfQt9fzqVGUfN6tx5QPlMOU2/4qZVdjsdDcwdJWlfydR1WWc4YWzHb6byNGjbugq55frozjtXZVSiHIIFaofu0TFUcqT/5B8RNtIS2RylOzUarTyMT034E/jqT9UFt7K/TFNrZGLZZHACM7E7+LSTqYPSXFj6/eIxyONXsVAidfvqx2auEj9iATjdKT/2BIaQjZAOL7z8lnJF4bnwbsW6DwQimImleKEIPES3ilYECUrZ2jJDOJD3QlhL3BtIfIl6TVo4F9kM1G1qjqTVwYmHlhQSpQfRpNWuoSvD78Vl/gO4iLKFUzu0RysfYAhxosT4SsQ0iLT5mVzaDWI5gmyn1T3U+DhWxYjh4J/Jhteg0EUWZoyaUsU3cbPiVPdNyDqPZrKYcZxLCp9Rn5yeZErt5kRlHztuvDwzTP+pZw9LaoQAVflFTSsPUi3Vpx2KhRL2I8nEla4SN64rdvotS6morHQfDaF8ebpcnOCpS81ktcwS18AcFAe9YC4Bn3uHCyK4fwYRTPq7cwGxVocEG9gDsynt+8s13LhKbBewj5oxyBRxP5z3hYoGpMrn0DauwKJAaeN8zKaevYL4C8gtPkbcXUyDUIIB7ZLOzEugfO7Wvw/DrZl+fpkupW/9xqpoclukBAfLivwBl2GcV+vz6i2rFpWs4EfUn0
  template:
    metadata:
      creationTimestamp: null
      name: {{.Chart.Name }}-index2
      namespace: default
    type: Opaque
