apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCjrrzQHRjFGumpwocQsDUmX+slbxSJwhrpTymWkvbwxrFfFmOfkLn9JJZYsDekDmBEVmtSQxW6xcHo81kRKffe9B5YpBSOo7tbk8t6mMBHdWbKwq3AUza3OP10dyoHCLhJ7wZJH/vfUSu9ZunRumJ5JI7ODKIYcvReo+9ULkMW3hcyoLIi3Jxi/36rgZ3aIrHAeV1ROm6lEPISquK5Ve4SzwP3imS1RUqMo0uIzaFawKrdaoode2cw41ihj/z5HBWNDoNSijrPaBEfCX+LWqnbU+o6tQRHVegStNzHHhFuzIQwE4jcQBkoA39bfOtNxzVj1OOvLhiL27jcDx7FvdbiySfY6SKDvcKlvlKoqW7m6IIo487EhhJDe+QirvPbyTRdQ8nPBo4AAepZTVQCEHU5uvufO9i70bF31smNKuwVctkweqP4yEhA4KTp3RrGqqCVDebw2s6UdWLfhC5qd9hHMKF/u6KtRo2mJgVD4W2/0lHUeI8aMj4uA4Wu8FCJ3UuU50NSTa5Tz+cNmV0zg7Oj7kV7Y9y0zO1XWQ5P6qCLmsa3W4KpLNFXIbTcBvr/SwjzeYV4pf7z8uN5Yj76LhArod+Osjz63tUrMjgSP+MsF6+qbQKLDCCRNyHyu6t9EAuGV+JwfMWo4RCPlO6OOjM9vkCTMDURMkfvFCRNH9h6ZibZ3jUMyn+PA5NAD9nwoWXv2Q6a7fA=
    username: AgBl3LdjsHnBXgGZWZ686txipkEGaWwCPjhg8vyxeEGmrGGnWUyrheuzx9YlnsVpCGKMFj775wFudzZJkKLN/CPIi8ab7Skvv/3Yg1CxK+XuISoXTfXonFVQAAkQ0I2davoJ4RJCPfyHR6q+djm1YvQwj+JPSCjD3X7V1G0E0qTvEeqPXUiSGp5pFQrZrNIUw8P8Ao2yAP6g0rLGI6Tpon+dEsl0aPbE4SF5CdIHGykp0K8Nq1sAzE+GR7L/iFKIn5R44DpA5oSGVgFRySZe9vfID0OpWFhTx8BprXrewfZlLN2sDb0r1P8gQ+Vpt59w49v/KcMYaSUVF+xTcTM3v26hTJZRFYoSJ/vSS5qN4N2qryY2mWe4RNSU7Udzz5MFjzyi40zqNDzt4VDscIkP3WUkjjBE+RySmr3ML2gm9bQHskXRe9gWaJwc6kgTQn6VGoGfCcjd/Ov3+SjBaIAsIGo56GdhAHNEsMsTN3+o3r/iFilbHfQ5UOgA9/W9SE/pn+ocx+t54u5SCtA4UedxS8a5jiFxbP2kALe1MlrPeyZdlmOqRPTH2M+bHRxZ7AdirH1Sd2wbl2sgcyo99jWJfEJ9+LfYLPQys5LXVJ1aU+hQxH82F8RT8KLJnt+7wH0KsZawdXqJLQzlT0uSDdPoYD/LxDM31a24kPhNTQOCvlg4KMgV3zGwCuTQq7ua9JhaMPzPVMdxWPw=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
